### ISSUE TITLE
When I change the page orientation come at the beginning of page

### ISSUE THREAD

**Issue by ahmerafzal1** [barteksc/AndroidPdfViewer#301]
**I am using this code**
```
.onRender(new OnRenderListener() {
@Override
public void onInitiallyRendered(int nbPages, float pageWidth, float pageHeight) {
pdfView.fitToWidth();
}
})
```
**to change the orientation of the page. But if I have to assume if the portrait mode and page number 15 in change page orientation of the page when we started the landscape.** 
<br><a href="https://ibb.co/g8M13F"><img src="https://preview.ibb.co/fbkTiF/Screenshot_20170529_174432.png" alt="Screenshot_20170529_174432" border="0"></a><br>
<a href="https://ibb.co/dV6eqv"><img src="https://preview.ibb.co/cDw13F/Screenshot_20170529_174443.png" alt="Screenshot_20170529_174443" border="0"></a><br>
**Please help me about this.**

**Comment by 1stmetro** [comment]
Save the page number when you change the orientation, then when reloading pass the page number and it will continue at the page when you changed orientation.

Simple enough to implement.

**Comment by ahmerafzal1** [comment]
@1stmetro Can you provide me a piece of code for it? Thanks in advance

**Comment by 1stmetro** [comment]
in the orientation code when you change the orientation simply save the integer and reload when the orientation changes.

.defaultPage(pageNumber)

**Comment by ahmerafzal1** [comment]
I'm trying to implement this method but fail 
```
protected void onSaveInstanceState(Bundle outState) {
  super.onSaveInstanceState(outState);
  outState.putInt("current_page", pageNumber);
}

public void onCreate(Bundle savedInstanceState) {
  if (savedInstanceState != null){
    pageNumber = savedInstanceState.getInt("current_page");
  }
}
```
Please place this method correctly, please send me correct code, I'll be very thankful

**Comment by 1stmetro** [comment]
Okay here is how to do what you are trying to do...

I believe i reload the activity in a different orientation when i change the orientation as i normally have the activity orientation set to portrait.

So simply pass the current page number via the intent variable and read the variable when loading the activity then simply pass the variable to pdfview and it will work as the page number is being passed via the intent.

To make it even better store the page number in sharedPreferences that way if you reload the activity at a later date the page will remain the same, 

Also store the filename and then you can always restore the page unless the filename changes otherwise a different pdf will always load at the stored page value, remember if the filename is different to the stored set the page number to zero.

Hopefully that gives a good insight on how to reload using a stored page number.

**Comment by barteksc** [comment]
@ahmerafzal1 Did you manage to fix this issue?

**Comment by ahmerafzal1** [comment]
Still not, I used 2 method but falied

**Comment by barteksc** [comment]
Store current page number in `onSaveInstanceState()` and then restore it in `onRestoreInstanceState()` or `onCreate()`. Finally call `pdfView.fitToWidth(storedPageNumber)`. That's it.

**Comment by ahmerafzal1** [comment]
Ok Thank you very much
