### ISSUE TITLE
Better handling of load exception without recycle first

### ISSUE THREAD

**Issue by dIeGoLi** [barteksc/AndroidPdfViewer#623]
Hello,
Thanks to all involved for this great library.

When calling load on the PDFView without recycling first following exception occurs:
IllegalStateException("Don't call load on a PDF View without recycling it first.")

This normally leads to an app crash because the load is posted as Runnable and the exception is not handled. The load method already receives as parameter an onErrorListener. Would it not be better to notify the onErrorListener and return? 
I would be able to contribute but would like to be interested in your opinion.

Greets Diego

**Comment by Flamedek** [comment]
I don't mind the current behaviour since it is a developer error so you want to fail fast to fix the issue.  
Having it call through to the OnErrorListener might just make it a little bit harder to find and debug.  

But on the other hand it is an error while loading the pdf so it makes sense to notify the listener.  

Would it not be possible to recycle the previous data, if any, and just load the new pdf without an error?

**Comment by dIeGoLi** [comment]
The current behaviour is not that bad because normally it is a developer error you find quite fast. Recycle is what you have to do. But if you make for example an error, where a load of the pdf is scheduled async twice, you could run into the issue as well. Generally it is just avoidable to produce an app crash. rather than being able to handle any exception. I would suggest to modify the behaviour that if an on error listener is specified than that one is notified, otherwise the current behaviour stays the same.
